config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  match 'preview/:id', :controller => 'deck', :action => 'preview', :via => [:get], as: :preview_deck
  get 'users/sign_up' => 'users#new', :as => :signup
  get ':username' => 'users#show', as: :profile , :constraints => { :username => /[0-9A-Za-z\-\.]+/ }
  post 'users' => 'users#create'
  match 'users/edit' => 'users#edit', :via => [:put, :get] , as: :edit_user
  match 'users' => 'users#delete', :via => [:delete]
  match 'users.json' =>  'users#update', :via => [:put]
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  get 'users/sign_out' => 'sessions#destroy'

  match ':username/new', :controller => 'editor', :action => 'new', :via => [:get], as: :new_deck, :constraints => { :username => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug/edit', :controller => 'editor', :action => 'edit', :via => [:get], :constraints => { :user => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug/live', :controller => 'live', :action => 'live', :via => [:get], as: :live, :constraints => { :user => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug', :controller => 'deck', :action => 'show', :via => [:get], as: :show_deck, :constraints => { :user => /[0-9A-Za-z\-\.]+/ }

  match 'api/v1/decks', :controller => 'deck', :action => 'decks', :via => [:post]
  match 'api/v1/decks/:id', :controller => 'deck', :action => 'decks', :via => [:put, :get, :delete]
  match 'api/v1/decks/:id/thumbnails', :controller => 'deck', :action => 'thumbnails', :via => [:get, :post], as: :deck_thumb
  match 'api/v1/decks/:id/fork', :controller => 'deck', :action => 'fork', :via => [:post]
  match 'api/v1/decks/:id/publish', :controller => 'deck', :action => 'publish', :via => [:post]
  match 'api/v1/decks/:id/stream', :controller => 'live', :action => 'stream', :via => [:get,:put]
  match 'api/v1/decks/:id/exports', :controller => 'exports', :action => 'export', :via => [:post]
  match 'api/v1/decks/:id/exports/:id_export', :controller => 'exports', :action => 'export', :via => [:get]
  match 'api/v1/status', :controller => 'deck', :action => 'status', :via => [:get]
  match 'api/v1/slide_templates', :controller => 'template', :action => 'slide_templates', :via => [:get]
  match 'api/v1/user_settings' , :controller => 'settings', :action => 'update', :via => [:put]
  match 'api/v1/media', :controller => 'medias', :action => 'media', :via => [:get,:post]
  match 'api/v1/media/:id', :controller => 'medias', :action => 'edit_media', :via => [:delete]
  match 'api/v1/tags', :controller => 'tags', :action => 'get_tags', :via => [:get]
  match 'api/v1/decks/:id/kudos/kudo', :controller => 'kudos', :action => 'kudo', :via => [:post]
  match 'api/v1/decks/:id/kudos/unkudo', :controller => 'kudos', :action => 'kudo', :via => [:delete]

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true

  has_attached_file :thumbnail
  validates_attachment :thumbnail, content_type: { content_type: "image/png" }

  def kudos
    Kudo.where(:deck_id=>self.id).count
  end

  def kudo_by_user(user_id)
    by_user = false
    if Kudo.where(:deck_id => self.id, :user => user_id).first
      by_user = true
    end
    by_user
  end

end

app/controllers/deck_controller.rb
class DeckController < ApplicationController
  skip_before_filter :verify_authenticity_token
  include ApplicationHelper

  def decks
    if request.post?
      create
    end
    if request.put?
      update
    end

    if request.get?
      get_deck
    end

    if request.delete? and params[:id]
      deck = Deck.find(params[:id])
      deck.delete
      render :nothing => true
    end
  end

  def fork
    if request.post? and params[:id]
      deck = Deck.find(params[:id])
      deck_forking = deck.dup
      deck_forking.title = "Copy of " + deck.title
      deck_forking.slug = deck.slug + "_copy"
      deck_forking.save

      redirect_to profile_url(current_user.username)
    end
  end

  def status
    if request.get?
      respond_to do |format|
        format.json {
          render json: {
              :user_signed_in => true,
              :app_version => "2457ee0"
              #:user=> {"id" : 546872, "username" : "ruby232", "name" : null, "description" : null, "thumbnail_url" : "https://www.gravatar.com/avatar/d56b941ba90e3d9ea677a36aa3823260?s=140\u0026d=https%3A%2F%2Fs3.amazonaws.com%2Fstatic.slid.es%2Fimages%2Fdefault-profile-picture.png", "pro" : false, "team_id" : null, "settings" : {"id" : 390818, "present_controls" : true, "present_upsizing" : true, "present_notes" : true, "editor_grid" : true, "editor_snap" : true, "developer_mode" : false }, "email" : "rubiselprieto@gmail.com", "notify_on_receipt" : true, "billing_address" : null, "editor_tutorial_completed" : true, "manually_upgraded" : false, "deck_user_editor_limit" : 1}
          }
        }
      end
    end
  end

  def create
    deck_param = params[:deck]
    @deck = Deck.new()
    @deck.title = deck_param[:title]
    @deck.slug = to_slug(deck_param[:title])
    @deck.description = deck_param[:description]
    @deck.data = deck_param[:data]
    @deck.comments_enabled= deck_param[:comments_enabled]
    @deck.forking_enabled = deck_param[:forking_enabled]
    @deck.auto_slide_interval = deck_param[:auto_slide_interval]
    @deck.transition = deck_param[:transition]
    @deck.background_transition = deck_param[:background_transition]
    @deck.theme_font = deck_param[:theme_font]
    @deck.theme_color = deck_param[:theme_color]
    @deck.should_loop = deck_param[:should_loop]
    @deck.rtl = deck_param[:rtl]
    @deck.share_notes = deck_param[:share_notes]
    @deck.slide_number = deck_param[:slide_number]
    @deck.rolling_links = deck_param[:rolling_links]
    @deck.center = deck_param[:center]
    @deck.user = current_user

    respond_to do |format|
      if @deck.save()
        format.json { render json: deck_json_response(@deck) }
      else
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    deck_param = params[:deck]

    @deck = Deck.find(params[:id])
    @deck.title = deck_param[:title]
    @deck.description = deck_param[:description]
    @deck.data = deck_param[:data]
    @deck.comments_enabled= deck_param[:comments_enabled]
    @deck.forking_enabled = deck_param[:forking_enabled]
    @deck.auto_slide_interval = deck_param[:auto_slide_interval]
    @deck.transition = deck_param[:transition]
    @deck.background_transition = deck_param[:background_transition]
    @deck.theme_font = deck_param[:theme_font]
    @deck.theme_color = deck_param[:theme_color]
    @deck.should_loop = deck_param[:should_loop]
    @deck.rtl = deck_param[:rtl]
    @deck.share_notes = deck_param[:share_notes]
    @deck.slide_number = deck_param[:slide_number]
    @deck.rolling_links = deck_param[:rolling_links]
    @deck.center = deck_param[:center]

    if deck_param[:custom_slug]
      @deck.slug = deck_param[:custom_slug]
    end


    respond_to do |format|
      if @deck.save()
        format.json { render json: deck_json_response(@deck) }
      else
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end

  end

  def get_deck
    @deck = Deck.find(params[:id])
    respond_to do |format|
      format.json { render json: deck_json_response(@deck) }
    end
  end

  # Ver como manejar las peticiones al preview
  def thumbnails
    @deck = Deck.find(params[:id])
    if request.post? or not @deck.thumbnail
      kit = IMGKit.new("#{request.host}/preview/#{params[:id]}", :width => 240, :height => 230)
      img = kit.to_img(:png)

      file = Tempfile.new(["thumbnail_#{@deck.id}", 'png'], 'tmp',
                          :encoding => 'ascii-8bit')
      file.write(img)
      file.flush
      @deck.thumbnail = file
      @deck.save
      file.unlink
    end

    if request.get?
      file = File.open(@deck.thumbnail.path, 'r')
      send_data(file.read, :type => "image/png", :disposition => 'inline')
    end

    if request.post?
      render :nothing => true
    end

  end

  def publish
    if request.post? and params[:visibility] and params[:id]
      deck = Deck.find(params[:id])
      deck.visibility = params[:visibility]
      deck.save
      respond_to do |format|
        format.json { render json: {deck: deck_json_response(deck)} }
      end
    end
  end

  def show
    if request.get? and params[:user] and params[:slug]
      @user = User.where(:username => params[:user]).first
      @deck = Deck.where(:slug => params[:slug], :user_id => @user.id).first
      @user_decks = Deck.where(:user_id => @user.id).where.not(id: @deck.id)
    end
  end

  def preview()
    @deck = Deck.find(params[:id])
    render "preview", :layout => false
  end

  private
  def deck_json_response(deck)
    return DeckSerializer.new(deck).to_json
  end

  def decks_params
    params.require(:deck).permit(:deck, :version)
  end

  def to_slug(ret)
    #strip the string
    ret = ret.strip

    #blow away apostrophes
    ret.gsub! /['`]/, ""

    # @ --> at, and & --> and
    ret.gsub! /\s*@\s*/, " at "
    ret.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
    ret.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '_'

    #convert double underscores to single
    ret.gsub! /_+/, "_"

    #strip off leading/trailing underscore
    ret.gsub! /\A[_\.]+|[_\.]+\z/, ""

    ret
  end

end

app/helpers/deck_helper.rb
module DeckHelper
end

app/views/deck/_list.html.erb
<ul class="decks visible" data-tab-id="personal">
  <% if @decks %>
      <% @decks.each do |deck| %>
          <li class="deck public is-owner"
              data-id="<%= deck.id %>"
              data-url="/<%= deck.user.username %>/<%= deck.slug %>"
              data-slug="<%= deck.slug %>"
              data-description="<%= deck.description %>"
              data-view-count="1"
              data-visibility="<%= deck.visibility %>"
              data-created-at="<%= deck.created_at %>"
              data-user-id="<%= deck.user.id %>"
              data-username="<%= deck.user.username %>">

            <%= link_to "", show_deck_url(deck.user.username, deck.slug), class: "deck-link" %>

            <div class="deck-thumbnail">
              <div class="deck-image" data-image-url="<%= deck_thumb_url(deck) %>"></div>
            </div>

            <h2 class="deck-title">
          <span class="deck-title-value is-interactive">
          <%= deck.title %>
        </span>
            </h2>

            <p class="deck-description">
          <span class="deck-description-value is-interactive">
            <%= deck.description %>
          </span>
            </p>

            <div class="deck-metadata">
              <span class="deck-metadata-item status">Created <%= deck.created_at %></span>
              <span class="deck-metadata-item views" data-tooltip="Views" data-tooltip-delay="500"><span class="icon i-eye"></span>1</span>
              <span class="deck-metadata-item kudos" data-tooltip="Kudos" data-tooltip-delay="500"><span class="icon i-heart-fill"></span>0</span>
            </div>
            <div class="deck-lock-icon icon i-lock-stroke is-interactive" data-tooltip="This deck is private"></div>
            <div class="deck-controls is-interactive">
              <div class="deck-controls-secondary">
                <button class="button outline grey delete l ladda-button" data-spinner-color="#777" data-style="zoom-out" data-tooltip="Delete">
                  <span class="icon i-trash-stroke"></span></button>
                <button class="button outline grey clone l ladda-button" data-spinner-color="#777" data-style="zoom-out" data-tooltip="Duplicate">
                  <span class="icon i-fork"></span></button>
                <button class="button outline grey visibility l ladda-button" data-spinner-color="#777" data-style="zoom-out" data-tooltip="Visibility">
                  <span class="icon i-lock-stroke"></span></button>
              </div>
              <button class="button outline edit l" data-tooltip="Edit"><span class="icon i-pen-alt2"></span></button>
              <%= link_to(live_url(deck.user.username, deck.slug), class: "button outline present l", tooltip: "Present") do %>
                  <span class="icon i-play"></span>
              <% end %>

              <a class="button outline mobile-remote l" href="/ruby232/deck/speaker" target="_blank"><span class="icon i-mobile"></span></a>
            </div>
          </li>
      <% end %>
  <% end %>
</ul>

app/views/deck/_thumbnail.html.erb
<li class="deck-thumbnail">
  <div class="deck-image" style="background-image: url(<%= deck_thumb_url(deck) %>)">
    <%= link_to "", show_deck_url(deck.user.username, deck.slug), class: "deck-link" %>
  </div>
  <footer class="deck-details">
    <a class="author" href="<%= deck.user.username %>">
      <span class="picture" style="background-image: url(<%= deck.user.avatar.url(:thumb) %>)"></span>
      <span class="name"><% if deck.user.name %><%= deck.user.name %><% else %><%= deck.user.username %><% end %></span>
    </a>
    <div class="stats">
      <div>7,730<span class="icon i-eye"></span></div>
    </div>
  </footer>
</li>

app/views/deck/_viewport.html.erb
<div class="reveal-viewport theme-font-<%= @deck.theme_font %> theme-color-<%= @deck.theme_color %>">
  <div class="reveal">
    <div class="slides">
      <% if @deck and @deck.data %>
          <%= raw @deck.data %>
      <% else %>
          <section></section>
      <% end %>
    </div>
  </div>
</div>

app/views/deck/live.html.erb
<!DOCTYPE html>
<html class="sl-root decks live
  <% if logged_in? %>live-server
  <% else %>live-client
  <% end %>">
<head>
  <meta name="viewport" content="width=1024, user-scalable=no"/>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Slides">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style"
        content="black-translucent"/>
  <%= csrf_meta_tags %>
  <title><%= @deck.title %></title>
  <%= stylesheet_link_tag '/deveal/css/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '/deveal/fonticons/slides/slides', media: 'all', 'data-turbolinks-track' => true %>
  <%= render 'layouts/css/deck' %>
</head>

<body>
<div class="page-loader visible">
  <div class="page-loader-inner">
    <div class="page-loader-spinner"></div>
  </div>
</div>
<%= render 'layouts/header' %>
<%= render 'deck/viewport' %>
<%= render 'layouts/js' %>
    <% if logged_in? %>
        <%= javascript_include_tag '/deveal/js/sl/views/live.server', 'data-turbolinks-track' => true %>
    <% else %>
        <%= javascript_include_tag '/deveal/js/sl/views/live.client', 'data-turbolinks-track' => true %>
    <% end %>
    <%= javascript_include_tag '/deveal/js/lib/socket.io/socket.io', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/deck/preview.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=1024, user-scalable=no"/>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Slides">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style"
        content="black-translucent"/>
  <%= csrf_meta_tags %>
  <title><%= @deck.title %></title>
  <%= stylesheet_link_tag '/deveal/css/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= render 'layouts/css/deck' %>
</head>
<body>
<%= render 'deck/viewport' %>
<%= javascript_include_tag '/deveal/bower_components/jquery/dist/jquery.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/moment/moment', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/headjs/dist/1.0.0/head.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/reveal.js/lib/js/classList', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/reveal.js/js/reveal', 'data-turbolinks-track' => true %>

<script>
  Reveal.initialize({
        controls: false
      }
  );
</script>
</body>
</html>

app/views/deck/show.html.erb
<% provide(:title, @deck.title + " by " + @user.username) %>
<% provide(:html_class, "decks show") %>

<% content_for :css_add do %>
    <%= render 'layouts/css/deck' %>
<% end %>

<% content_for :js_add do %>
    <%= javascript_include_tag '/deveal/js/sl/views/decks.show', 'data-turbolinks-track' => true %>
<% end %>

<div class="marquee">

  <div class="reveal-frame">
    <%= render 'deck/viewport' %>
  </div>

  <div class="deck-kudos">
    <button class="kudos-button kudos-trigger" data-kudos-id="<%= @deck.id %>" data-kudoed-by-user="<% if logged_in? %><%= @deck.kudo_by_user(current_user) %><% end %>">
      <div class="kudos-heart">
        <span class="kudos-icon icon i-heart-fill"></span>
      </div>
      <div class="kudos-count" data-kudos-value="<%= @deck.kudos %>" data-kudos-id="<%= @deck.id %>"></div>
    </button>
  </div>

  <div class="pill summary-pill">
    <div class="pill-picture" style="background-image: url(<%= @deck.user.avatar.url(:thumb) %>)"></div>
    <div class="pill-content">
      <h4 class="pill-title"><%= @deck.title %></h4>

      <p class="pill-description">By <%= @deck.user.get_name %></p>
    </div>
  </div>

  <div class="pill instructions-pill">
    <div class="pill-picture"></div>
    <div class="pill-content">
      <h4 class="pill-title"></h4>

      <p class="pill-description"></p>
    </div>
  </div>

</div>

<div class="column">
  <header class="deck-info">
    <div class="deck-promotion">
      <a class="button cta" data-tooltip="Open the Present view" href="<%= live_url(@deck.user.username, @deck.slug) %>">Present</a>
    </div>

    <div class="deck-options">
      <a class="fullscreen-button" data-tooltip="Fullscreen" href="#"><span class="icon i-fullscreen"></span></a>
      <a class="comment-button" data-tooltip="Comments" data-scroll-to href="#comments" data-scroll-to data-scroll-to-offset="-90"><span class="icon i-comment-stroke"></span></a>
      <a class="fork-button" data-tooltip="Fork this deck" href="#"><span class="icon i-fork"></span></a>
      <a class="edit-button" data-tooltip="Edit" href="/<%= @deck.user.username %>/<%= @deck.slug %>/edit"><span class="icon i-pen-alt2"></span></a>
    </div>

    <div class="clear"></div>

    <div class="details">
      <div class="deck-info">
        <h3 class="title"><%= @deck.title %></h3>

        <p class="description">
          <a class="" href="/<%= @deck.user.username %>/<%= @deck.slug %>/edit?l=settings">Edit deck title &amp;
            description</a>
        </p>
        <ul class="deck-meta">
          <li data-tooltip="Published date" data-tooltip-delay="500">
            <span class="icon i-clock"></span>
            <time class="value ago" datetime="<%= @deck.created_at  %>"></time>
          </li>
          <li data-tooltip="Kudos" data-tooltip-delay="500">
            <span class="icon i-heart-fill"></span>
            <span class="value" data-kudos-value="1" data-kudos-id="769001"></span>
          </li>
          <li data-tooltip="Views" data-tooltip-delay="500">
            <span class="icon i-eye"></span>
            <span class="value">2</span>
          </li>
        </ul>
      </div>

      <div class="user-info">
        <% if current_user and current_user.id == @deck.user.id %>
        <a class="icon i-cog edit" href="/users/edit" data-tooltip="Account settings"></a>
            <% end %>

        <div class="picture" style="background-image: url(<%= @deck.user.avatar.url(:thumb) %>)"></div>
        <div class="text">
          <h3 class="title">
            <a href="/<%= @deck.user.username %>" class="username"><%= @deck.user.get_name %></a>
          </h3>

          <p class="description"><%= @deck.user.description %></p>
          <ul class="links">
          </ul>
        </div>
        <div class="clear"></div>
      </div>

      <div class="clear"></div>
    </div>
  </header>

  <section class="comments" id="comments">
    <div id="disqus_thread"><span class="placeholder">Loading comments...</span></div>
  </section>

  <section class="deck-list">
    <h2>More from <a href="/<%= @deck.user.username %>" ><%= @deck.user.get_name %></a></h2>
    <ul class="carousel">
      <% @user_decks.each do |deck| %>
          <%= render :partial => 'deck/thumbnail', :locals => {:deck => deck}  %>
      <% end %>
    </ul>
  </section>

</div>