config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  match 'preview/:id', :controller => 'deck', :action => 'preview', :via => [:get], as: :preview_deck
  get 'users/sign_up' => 'users#new', :as => :signup
  get ':username' => 'users#show', as: :profile , :constraints => { :username => /[0-9A-Za-z\-\.]+/ }
  post 'users' => 'users#create'
  match 'users/edit' => 'users#edit', :via => [:put, :get] , as: :edit_user
  match 'users' => 'users#delete', :via => [:delete]
  match 'users.json' =>  'users#update', :via => [:put]
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  get 'users/sign_out' => 'sessions#destroy'

  match ':username/new', :controller => 'editor', :action => 'new', :via => [:get], as: :new_deck, :constraints => { :username => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug/edit', :controller => 'editor', :action => 'edit', :via => [:get], :constraints => { :user => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug/live', :controller => 'live', :action => 'live', :via => [:get], as: :live, :constraints => { :user => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug', :controller => 'deck', :action => 'show', :via => [:get], as: :show_deck, :constraints => { :user => /[0-9A-Za-z\-\.]+/ }

  match 'api/v1/decks', :controller => 'deck', :action => 'decks', :via => [:post]
  match 'api/v1/decks/:id', :controller => 'deck', :action => 'decks', :via => [:put, :get, :delete]
  match 'api/v1/decks/:id/thumbnails', :controller => 'deck', :action => 'thumbnails', :via => [:get, :post], as: :deck_thumb
  match 'api/v1/decks/:id/fork', :controller => 'deck', :action => 'fork', :via => [:post]
  match 'api/v1/decks/:id/publish', :controller => 'deck', :action => 'publish', :via => [:post]
  match 'api/v1/decks/:id/stream', :controller => 'live', :action => 'stream', :via => [:get,:put]
  match 'api/v1/decks/:id/exports', :controller => 'exports', :action => 'export', :via => [:post]
  match 'api/v1/decks/:id/exports/:id_export', :controller => 'exports', :action => 'export', :via => [:get]
  match 'api/v1/status', :controller => 'deck', :action => 'status', :via => [:get]
  match 'api/v1/slide_templates', :controller => 'template', :action => 'slide_templates', :via => [:get]
  match 'api/v1/user_settings' , :controller => 'settings', :action => 'update', :via => [:put]
  match 'api/v1/media', :controller => 'medias', :action => 'media', :via => [:get,:post]
  match 'api/v1/media/:id', :controller => 'medias', :action => 'edit_media', :via => [:delete]
  match 'api/v1/tags', :controller => 'tags', :action => 'get_tags', :via => [:get]
  match 'api/v1/decks/:id/kudos/kudo', :controller => 'kudos', :action => 'kudo', :via => [:post]
  match 'api/v1/decks/:id/kudos/unkudo', :controller => 'kudos', :action => 'kudo', :via => [:delete]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks, dependent: :destroy
  has_one :setting , dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :username, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  has_attached_file :avatar,
                    :styles => {
                        :thumb => ['100x100#', :jpg, :quality => 70],
                        :preview => ['480x480#', :jpg, :quality => 70],
                        :large => ['600>', :jpg, :quality => 70],
                        :retina => ['1200>', :jpg, :quality => 30]
                    },
                    :convert_options => {
                        :thumb => '-set colorspace sRGB -strip',
                        :preview => '-set colorspace sRGB -strip',
                        :large => '-set colorspace sRGB -strip',
                        :retina => '-set colorspace sRGB -strip -sharpen 0x0.5'
                    },
                    default_url: "/images/user-default.png"
  validates_attachment :avatar,
                       content_type: {content_type: /^image\/(jpeg|png|svg)$/}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    if remember_digest.nil?
      false
    else
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def get_name
    if name
      name
    else
      username
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  require 'bcrypt'

  def show
    if params[:username]
      @user = User.where(:username => params[:username]).first
    end

    if params[:ID]
      @user = User.find(params[:id])
    end

    @decks=Deck.where(user_id: @user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user

      setting = Setting.new
      setting.user = @user
      setting.save

      redirect_to profile_url(@user.username)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(current_user.id)
    if request.put?
      @user.name = user_params[:name]
      @user.description = user_params[:description]
      @user.username = user_params[:username]
      @user.email = user_params[:email]
      if user_params[:avatar]
      @user.avatar = user_params[:avatar]
      end

      #Falta editar la contraseña
=begin
      if user_params[:password] and @user.authenticate(user_params[:current_password])
        @user.password = user_params[:password]
      end
=end

      if @user.save
        redirect_to profile_url(@user.username)
      end
    end

    if request.get?
      render 'edit'
    end
  end

  def update
    if request.put?
      respond_to do |format|
        format.json {
          render json: {
               }
        }
      end
    end
  end

  def delete
    current_user.destroy
    redirect_to root
  end

  private
  def user_params
    params.require(:user).permit(:name,:description,:username, :email, :password,
                                 :password_confirmation, :avatar, :current_password)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Account Settings") %>
<% provide(:html_class, "registrations edit") %>

<% content_for :js_add do %>
    <%= javascript_include_tag '/deveal/js/sl/util/validate', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '/deveal/js/sl/components/form_unit', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '/deveal/js/sl/views/devise.all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '/deveal/js/sl/views/devise.edit', 'data-turbolinks-track' => true %>
<% end %>

<div id="main" class="main" role="main">
  <div class="column thin">
    <section>
      <h2>Account settings</h2>

      <%= form_for @user, :url => edit_user_url(@user), :method => :put do |f| %>
          <%= render 'shared/error_messages', object: @user %>

          <div class="unit name" data-required="">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>

          <div class="unit text" data-validate="username" data-required>
            <%= f.label :username %>
            <%= f.text_field :username %>
          </div>

          <div class="unit text" data-validate="description">
            <%= f.label :description %>
            <%= f.text_field :description %>
          </div>

          <div class="photo-editor" data-photo-type="avatar">
            <p class="form-label">Profile photo</p>
            <div class="profile-photo">
              <div class="picture" style="background-image: url(<%= @user.avatar.url(:thumb) %>)"></div>
              <div class="description">
                <%= f.file_field :avatar %>
              </div>
            </div>
          </div>

          <div class="clear"></div>

          <div class="unit text" data-validate="email" data-required="">
            <%= f.label :email %>
            <%= f.text_field :email %>
          </div>

          <div class="unit text" data-validate="password">
            <label for="user_password">New password</label>
            <input autocomplete="off" id="user_password" name="user[password]" placeholder="leave blank if you don't want to change it" type="password">
          </div>

          <div class="unit text hidden" data-validate="password" data-required="">
            <label for="user_current_password">Current password</label>
            <input autocomplete="off" id="user_current_password" name="user[current_password]" placeholder="needed to confirm your changes" type="password">
          </div>

          <div class="clear"></div>

          <div class="actions">
            <%= f.button "Submit", class: "button xl ladda-button", data_style: "expand-right", name: "button", type: "submit" %>
            <%= link_to "Cancel", profile_url(current_user.username), class: "button outline low-contrast xl" %>
          </div>

      <% end %>

      <div class="devise-links">
        <a href="#" class="delete-account-toggle">Delete account</a>
      </div>

      <div class="delete-account">
        <p>Your account including all of your decks will be permanently deleted. This can <b>not</b> be undone.</p>
        <a class="button negative grey" data-confirm="Are you sure you want to delete your account?" data-method="delete" href="/users" rel="nofollow">I
          understand, delete my account</a>
      </div>

    </section>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Create an account") %>
<% provide(:html_class, "users new") %>

<div class="column wide">
      <hgroup class="funnel-intro"><h2>Create an account</h2></hgroup>
        <section class="auth">
        <div class="auth-options">
          <div class="auth-option">
            <%= form_for(@user) do |f| %>
                <%= render 'shared/error_messages', object: @user %>

                <div class="unit text" data-validate="username" data-required >
                  <%= f.label :username %>
                  <%= f.text_field :username %>
                </div>

                <div class="unit text" data-validate="email" data-required >
                  <%= f.label :email %>
                  <%= f.text_field :email %>
                </div>

                <div class="unit text" data-validate="password" data-required >
                  <%= f.label :password %>
                  <%= f.password_field :password %>

                  <%= f.label :password_confirmation, "Confirmation" %>
                  <%= f.password_field :password_confirmation %>
                </div>

                <div class="actions">
                  <%= f.button "Submit", class: "button xl ladda-button", data_style: "expand-right", name: "button", type:"submit" %>
                </div>

            <% end %>
          </div>

          <div class="clear"></div>
        </div>
      </section>
    </div>

app/views/users/show.html.erb
<% provide(:title, "Presentations by " + @user.username) %>
<% provide(:html_class, "users show") %>

<% content_for :js_add do %>
    <%= javascript_include_tag '/deveal/js/sl/views/users.show', 'data-turbolinks-track' => true %>
<% end %>

<div class="column">
  <section class="presentations">

    <div class="user-info">
      <a class="icon i-cog edit" href="/users/edit" data-tooltip="Account settings"></a>
      <div class="picture" style="background-image: url(<%= @user.avatar.url(:thumb) %>)"></div>
      <div class="text">
        <h3 class="title">
          <%= link_to @user.username,profile_url(@user.username),class: "username"  %>
        </h3>
        <p class="description"></p>
        <ul class="links">
        </ul>
      </div>
      <div class="clear"></div>
    </div>

    <div class="deck-filters sl-form">
      <div class="deck-filters-search-wrapper">
        <input class="deck-filters-search" type="text" placeholder="Search..." required>
        <span class="deck-filters-search-clear icon i-x-altx-alt" data-tooltip="Clear"></span>
      </div>
      <button class="button outline deck-filters-sort">Newest first</button>
    </div>

    <%= render 'deck/list' %>

  </section>
</div>