config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  match 'preview/:id', :controller => 'deck', :action => 'preview', :via => [:get], as: :preview_deck
  get 'users/sign_up' => 'users#new', :as => :signup
  get ':username' => 'users#show', as: :profile , :constraints => { :username => /[0-9A-Za-z\-\.]+/ }
  post 'users' => 'users#create'
  match 'users/edit' => 'users#edit', :via => [:put, :get] , as: :edit_user
  match 'users' => 'users#delete', :via => [:delete]
  match 'users.json' =>  'users#update', :via => [:put]
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  get 'users/sign_out' => 'sessions#destroy'

  match ':username/new', :controller => 'editor', :action => 'new', :via => [:get], as: :new_deck, :constraints => { :username => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug/edit', :controller => 'editor', :action => 'edit', :via => [:get], :constraints => { :user => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug/live', :controller => 'live', :action => 'live', :via => [:get], as: :live, :constraints => { :user => /[0-9A-Za-z\-\.]+/ }
  match ':user/:slug', :controller => 'deck', :action => 'show', :via => [:get], as: :show_deck, :constraints => { :user => /[0-9A-Za-z\-\.]+/ }

  match 'api/v1/decks', :controller => 'deck', :action => 'decks', :via => [:post]
  match 'api/v1/decks/:id', :controller => 'deck', :action => 'decks', :via => [:put, :get, :delete]
  match 'api/v1/decks/:id/thumbnails', :controller => 'deck', :action => 'thumbnails', :via => [:get, :post], as: :deck_thumb
  match 'api/v1/decks/:id/fork', :controller => 'deck', :action => 'fork', :via => [:post]
  match 'api/v1/decks/:id/publish', :controller => 'deck', :action => 'publish', :via => [:post]
  match 'api/v1/decks/:id/stream', :controller => 'live', :action => 'stream', :via => [:get,:put]
  match 'api/v1/decks/:id/exports', :controller => 'exports', :action => 'export', :via => [:post]
  match 'api/v1/decks/:id/exports/:id_export', :controller => 'exports', :action => 'export', :via => [:get]
  match 'api/v1/status', :controller => 'deck', :action => 'status', :via => [:get]
  match 'api/v1/slide_templates', :controller => 'template', :action => 'slide_templates', :via => [:get]
  match 'api/v1/user_settings' , :controller => 'settings', :action => 'update', :via => [:put]
  match 'api/v1/media', :controller => 'medias', :action => 'media', :via => [:get,:post]
  match 'api/v1/media/:id', :controller => 'medias', :action => 'edit_media', :via => [:delete]
  match 'api/v1/tags', :controller => 'tags', :action => 'get_tags', :via => [:get]
  match 'api/v1/decks/:id/kudos/kudo', :controller => 'kudos', :action => 'kudo', :via => [:post]
  match 'api/v1/decks/:id/kudos/unkudo', :controller => 'kudos', :action => 'kudo', :via => [:delete]

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true

  has_attached_file :thumbnail
  validates_attachment :thumbnail, content_type: { content_type: "image/png" }

  def kudos
    Kudo.where(:deck_id=>self.id).count
  end

  def kudo_by_user(user_id)
    by_user = false
    if Kudo.where(:deck_id => self.id, :user => user_id).first
      by_user = true
    end
    by_user
  end

end

app/models/export.rb
class Export < ActiveRecord::Base
  belongs_to :deck
  belongs_to :user
end

app/models/kudo.rb
class Kudo < ActiveRecord::Base
  belongs_to :user
  belongs_to :deck

end

app/models/media.rb
class Media < ActiveRecord::Base
  has_attached_file :file,
                    :styles => {
                        :thumb => ['100x100#', :jpg, :quality => 70],
                        :preview => ['480x480#', :jpg, :quality => 70],
                        :large => ['600>', :jpg, :quality => 70],
                        :retina => ['1200>', :jpg, :quality => 30]
                    },
                    :convert_options => {
                        :thumb => '-set colorspace sRGB -strip',
                        :preview => '-set colorspace sRGB -strip',
                        :large => '-set colorspace sRGB -strip',
                        :retina => '-set colorspace sRGB -strip -sharpen 0x0.5'
                    }
  validates_attachment :file,
                       content_type: {content_type: /^image\/(jpeg|png|svg)$/}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  belongs_to :deck
  #status [initial, start, finish]
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks, dependent: :destroy
  has_one :setting , dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :username, presence: true, length: {maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  has_attached_file :avatar,
                    :styles => {
                        :thumb => ['100x100#', :jpg, :quality => 70],
                        :preview => ['480x480#', :jpg, :quality => 70],
                        :large => ['600>', :jpg, :quality => 70],
                        :retina => ['1200>', :jpg, :quality => 30]
                    },
                    :convert_options => {
                        :thumb => '-set colorspace sRGB -strip',
                        :preview => '-set colorspace sRGB -strip',
                        :large => '-set colorspace sRGB -strip',
                        :retina => '-set colorspace sRGB -strip -sharpen 0x0.5'
                    },
                    default_url: "/images/user-default.png"
  validates_attachment :avatar,
                       content_type: {content_type: /^image\/(jpeg|png|svg)$/}

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    if remember_digest.nil?
      false
    else
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def get_name
    if name
      name
    else
      username
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deck_helper.rb
module DeckHelper
end

app/helpers/editor_helper.rb
module EditorHelper

end

app/helpers/kudos_helper.rb
module KudosHelper
end

app/helpers/live_helper.rb
module LiveHelper
end

app/helpers/medias_helper.rb
module MediasHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/template_helper.rb
module TemplateHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="global-footer">
  <div class="link-group">
    <h5>Product</h5>
    <a href="https://slideme.com/">Home</a>
  </div>

  <div class="link-group">
    <h5>Help</h5>
    <a href="http://help.slides.com" target="_blank">Forum</a>
    <a href="http://help.slides.com/knowledgebase" target="_blank">Knowledge Base</a>
  </div>

  <div class="link-group">
    <h5>News</h5>
    <a href="http://blog.slideme.com" target="_blank">Blog</a>
    <a href="http://twitter.com/slideme" target="_blank">Twitter</a>
    <a href="http://facebook.com/slidemeapp" target="_blank">Facebook</a>
    <a href="http://plus.google.com/+slidemeapp/" rel="publisher" target="_blank">Google+</a>
  </div>

  <div class="link-group">
    <h5>Company</h5>
    <a href="https://slideme.com/about">About Slides</a>
  </div>

  <div class="copyright">
    <span>© 2016 Slideme</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="global-header ">
  <div class="wrapper">
    <div class="logo">
      <a class="home" href="/">
        <h1>Slideme</h1>
      </a>
    </div>
    <ul class="nav ">
<!--      <li class="nav-item" data-page-id="e">
        <a class="nav-item-anchor" href="/explore"><span class="nav-item-label">Explore</span></a>
      </li>
      <li class="nav-item-divider"></li>-->

      <% if not logged_in? %>
    <li class="nav-item" data-page-id="sessions/new">
        <a class="nav-item-anchor" href="/users/sign_in"><span class="nav-item-label">Log in</span></a>
      </li>
      <li class="nav-item nav-item-highlighted nav-item-secondary" data-page-id="static/pricing">
        <%= link_to( { :controller => "users", :action => "new" }, class: "nav-item-anchor") do %>
            <span class="nav-item-label">Sign up</span>
        <% end %>
      </li>
      <% else %>
          <li class="nav-item profile-button">
            <%= link_to(profile_url(current_user.username),class: "nav-item-anchor") do %>
                <span class="nav-item-label"><%= current_user.username %></span>
            <span class="nav-item-burger">
              <span class="nav-item-burger-1"></span>
              <span class="nav-item-burger-2"></span>
              <span class="nav-item-burger-3"></span>
            </span>
            <% end %>

          </li>
      <% end %>
    </ul>
  </div>
</header>

<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/_js.html.erb
<%= render 'layouts/slconfig' %>

<script>
  window.SL = function (t) {
    t = t.split(".");
    for (var e = SL; t.length;) {
      var i = t.shift();
      e[i] || (e[i] = {}), e = e[i]
    }
    return e
  };
</script>

<%= javascript_include_tag '/deveal/bower_components/jquery/dist/jquery.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/tinycolor/dist/tinycolor-min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/moment/moment', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/headjs/dist/1.0.0/head.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/reveal.js/lib/js/classList', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/reveal.js/js/reveal', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/cryptojslib/rollups/md5', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/bower_components/js-signals/dist/signals.min', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/vendor/changeElementType/changeElementType', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/vendor/ladda/dist/ladda.jquery.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/vendor/ladda/dist/spin.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/vendor/ladda/dist/ladda.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/vendor/pasteImageReader/jquery.paste_image_reader', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/lib/modernizr', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/webfon', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/throttle', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/class', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/v_event', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/vkbeautify', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/ckeditor/ckeditor', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/lib/tabby', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/util/util', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/device', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/html', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/deck', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/color', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/user', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/string', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/trig', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/svg', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/dom', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/math', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/selection', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/util/anim', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/collections/collection', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/collections/loadable', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/collections/media_tags', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/collections/media', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/models/model', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/user_membership', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/user_settings', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/user', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/deck', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/media_tag', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/media', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/theme', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/models/template', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/data/templates', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/helpers/file_uploader', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/helpers/page_loader', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/helpers/poll_job', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/helpers/theme_controller', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/helpers/stream_editor', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/helpers/stream_live', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/helpers/fullscreen', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/popup/popup', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/popup/all', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/components/header', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/menu', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/scroll_shadow', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/templates_page', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/templates', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/notification', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/retry_notification', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/text_editor', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/theme_options', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/prompt', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/kudos', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/context_menu', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/collab/collaboration', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/components/collab/all', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/views/base', 'data-turbolinks-track' => true %>

<%= javascript_include_tag '/deveal/js/sl/config', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/settings', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/keyboard', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/pointer', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/routes', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/session', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/warnings', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/draganddrop', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/fonts', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/visibility', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/templates', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/markup', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/sidebar', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/activity', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/locale', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/notify', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/deveal/js/sl/tooltip', 'data-turbolinks-track' => true %>

<%= yield(:js_add) %>

<%= javascript_include_tag '/deveal/js/app', 'data-turbolinks-track' => true %>

app/views/layouts/_slconfig.html.erb
<%= javascript_tag do %>
    var SLConfig = {
    <% if logged_in? %> "current_user":  <%= raw UserSerializer.new(current_user).to_json %>,<% end %>
    <% if @deck %>"deck": <%= raw DeckSerializer.new(@deck).to_json %><% end %>
    };
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="sl-root <%= yield(:html_class) %>" data-editor-version="2" data-visibility="all">
<head>
  <meta name="viewport" content="width=1024, user-scalable=no"/>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Deveal">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style"
        content="black-translucent"/>
  <%= csrf_meta_tags %>


  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag '/deveal/vendor/ladda/dist/ladda.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '/deveal/vendor/ladda/dist/ladda-themeless.min', media: 'all', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag '/deveal/css/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '/deveal/fonticons/slides/slides', media: 'all', 'data-turbolinks-track' => true %>
  <%= yield(:css_add) %>
</head>

<body>
<div id="container" class="container">
  <%= render 'layouts/header' %>

  <div id="main" class="main" role="main">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</div> <!--! end of #container -->

<%= render 'layouts/js' %>
</body>
</html>

app/views/layouts/css/_color.html.erb
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/asphalt-orange', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/beige-brown', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/black-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/black-mint', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/black-orange', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/blue-yellow', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/cobalt-orange', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/coral-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/forest-yellow', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/grey-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/mint-beige', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/no-color', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/sand-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/sea-yellow', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/silver-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/silver-green', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/sky-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/white-blue', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/css/deck/theme-color/yellow-black', media: 'all', 'data-turbolinks-track' => true %>

app/views/layouts/css/_deck.html.erb
<%= stylesheet_link_tag '/deveal/css/deck/highlight', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag '/deveal/bower_components/reveal.js/css/reveal', media: 'all', 'data-turbolinks-track' => true %>
<% if @editor %>
    <%= render 'layouts/css/color', :editor => true %>
    <%= render 'layouts/css/font', :editor => true %>
<% end %>
<% if @deck and not @editor%>
    <%= stylesheet_link_tag "/deveal/css/deck/theme-color/#{@deck.theme_color}", media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "/deveal/css/deck/theme-font/#{@deck.theme_font}", media: 'all', 'data-turbolinks-track' => true %>
<% end %>
<%= stylesheet_link_tag '/deveal/css/deck/deck', media: 'all', 'data-turbolinks-track' => true %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li>* <%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>